### PR TITLE
Third milestone

### PR DESCRIPTION
**Pull request by MkrtichSargsyan**
In this pull request, the code shows how the associations between the user model and itself for creating friendships are done with only two lines.

1. When a friendship is created, an inverse_friendship is automatically created also, to reflect that request to the invited user.
2. Is possible to find the user's friends in the friendship table by user_id.
3. Is possible to access the requests sent from the user to another user through the friends method on that user.
4. Is possible to access the requests sent to the user from another user through the inverse_friendships method on that user.

### CODE REVIEW

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far, everything works fine, but there are a few more things required. 
### General

- [x] You should be very Professional when writing commits, I know bugs can get you mad but you have to keep your cool.

- [ ] in order to get all posts written by user on their friends, you can use simple method in User model (in order to NOT do it with Enumerables)

##### User model
````ruby
def friends_and_own_posts
  Post.where(user: (self.friends << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
````
- [ ]  Instead of processing objects in application memory, let's define association with SQL query.
````ruby
# confirm friends
has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "Friendship"
has_many :friends, through: :confirmed_friendships

# pending_friends
has_many :pending_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend

#friend_requests
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "Friendship", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships

`````
- [x] I couldn't run this project locally because of this error



### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team. 💻 👀 ✨ 

## However, there are some changes required 👀 🧰 🔨 🔧 

- Instead of having the `accept` method in your `users_controller`, please add something like this to your `friendships` model:
```
def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
- Similarly, please generate the complete list of posts by friends and self with something like this in the `User` model:
```ruby
def friends_and_own_posts
  Post.where(user: (self.friends << self))
  # This will produce SQL query with IN. Something like: select * from posts where user_id IN (1,45,874,43);
end
```

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done really well in this milestone.
However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] I can see that you've added the `confirm_friend` method in the `Friendship` model, just as you've added the `friends_and_own_posts` method in the `User` model. However, you're not using these methods in any controller action. 
- Since you've added the methods, let's see them in action. For instance, the `confirm_friend` method can be used in the `accept` action in your `users_controller`.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've made laudable progress in this milestone.
However, some changes are required before this project can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] When friendship is confirmed, an additional row with reversed user-friend pair should be created
- Removing the inverse friendship part of the `confirm_friend` method will not create this additional row. Kindly restore the concluding part of the `confirm_friend` method so that this goal can be achieved. 
- Your `confirm_friend` method should look like this:

```ruby
# Friendship model

def confirm_friend
  self.update_attributes(confirmed: true)
  Friendship.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```

- [ ] Do not forget to use the `friends_and_own_posts` in action too. You've already added the method to your `User` model, but it is not used in any of the actions.


* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] as the previous TSE mentioned, please use `friends_and_own_posts` instead of `timeline_posts` ins your Posts#Index
  - all query handling should be in the model, not the controller

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Mike Sargsyan** 
Good job with the improvements for this project :muscle:  :muscle:
It meets most of the requirements :clap: :clap: :clap:  
There are just a couple of details to improve before you can go ahead:

- [ ] Add a screenshot to the README file
- [ ] There is a mistake in the way you're creating the friendship association, for this milestone each friendship should add a couple of rows in the Friendship database, both with a confirmable value equal to false, if the friendship is accepted then both rows are updated with confirmable value equals true if friendship is rejected then both rows are removed.
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED ♻️ 
A great effort implementing the requested changes 👍 
You are almost there, just a few adjustments and ready to go 🚀 
Kindly check my comments below 👇  apply the changes and resubmit your project for a new code review ⏩ 
Good luck 😺 
## Mandatory changes
- Add tests for all the association's, scopes, helper methods...in your models
- Add integration tests for all the features of your application

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @Team! 👋 👋 

### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended**
- [ ] Please add more tests to your project. 
- Add tests for all the association's, scopes, helper methods...in your models.
- Add integration tests for all the features of your application
- Add negative test case scenarios as well.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 

Great job guys :clap: :clap: :clap: :clap:, thanks for making the required changes by the previous TSE's :100: :+1: :1st_place_medal: 

now you can merge your milestone is approved :checkered_flag:.

## Happy Coding :tophat:

**Pull request merged**
